//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Byporten
{
    using System;
    using System.Collections.Generic;
    
    public partial class aktuelt
    {
        public int Id { get; set; }
        public string Tittel { get; set; }
        public string Innhold { get; set; }
        public string Startdato { get; set; }
        public string Sluttdato { get; set; }
        public string Bilde { get; set; }
    }
}
