//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Byporten
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class availablepositions
    {
        public int Id { get; set; }
        
        [Required(ErrorMessage="Feltet er påkrevd")]
        [MinLength(6, ErrorMessage="Feltet er for kort"), MaxLength(100, ErrorMessage="Feltet er for langt")]
        public string Title { get; set; }

        [Required(ErrorMessage="Feltet er påkrevd")]
        [MinLength(3, ErrorMessage="Feltet er for kort"), MaxLength(3000, ErrorMessage="Feltet er for langt")]
        public string Description { get; set; }

        [Required(ErrorMessage="Feltet er påkrevd")]
        [MinLength(8, ErrorMessage="Feltet er for kort"), MaxLength(128, ErrorMessage="Feltet er for langt")]
        public string CreateDate { get; set; }

        [Required(ErrorMessage="Feltet er påkrevd")]
        [MinLength(8, ErrorMessage="Feltet er for kort"), MaxLength(128, ErrorMessage="Feltet er for langt")]
        public string ExpireDate { get; set; }
        public string ImageURL { get; set; }
        public string ExternalLinkURL { get; set; }
    }
}
