//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Byporten
{
    using System;
    using System.Collections.Generic;
    
    public partial class bplususer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string EmailRepeat { get; set; }
        public string PhoneNumber { get; set; }
        public string Gender { get; set; }
        public string Birthdate { get; set; }
        public string Zipcode { get; set; }
        public string BirthYearChild1 { get; set; }
        public string BirthYearChild2 { get; set; }
        public string BirthYearChild3 { get; set; }
        public string BirthYearChild4 { get; set; }
        public string Interests { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
    }
}
