//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Byporten
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int UserID { get; set; }
        public string Name { get; set; }

        public string Gender { get; set; }
        public string Email { get; set; }

        public string RepeatEmail { get; set; }

        public string PhoneNumber { get; set; }
        public string Birthdate { get; set; }

        public string Interests { get; set; }

        public string Children { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }

        public string Knowledge { get; set; }
    }
}
